import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Course from './models/Course.js';
import User from './models/User.js';

dotenv.config();

const slugify = (text) =>
  text
    .toLowerCase()
    .trim()
    .replace(/[^\w\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/--+/g, '-');

const courses = [
  {
    title: 'Complete React Developer Bootcamp',
    description: 'Master React from scratch to advanced patterns. Learn hooks, context, Redux Toolkit, React Query, and build 5 real projects including a full-stack e-commerce app.',
    shortDescription: 'Master modern React with hooks, Redux, and 5 real-world projects.',
    instructor: 'Sarah Chen',
    instructorBio: 'Senior Frontend Engineer at Google with 10+ years of React experience.',
    category: 'Web Development',
    level: 'Intermediate',
    duration: '48 hours',
    price: 89.99,
    isFree: false,
    thumbnail: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800&q=80',
    previewVideoUrl: 'https://www.youtube.com/embed/w7ejDZ8SWv8',
    rating: 4.9,
    reviewCount: 2847,
    enrolledCount: 18420,
    tags: ['React', 'JavaScript', 'Frontend', 'Redux'],
    lessons: [
      { title: 'Welcome & Course Overview', duration: '8 min', videoUrl: 'https://www.youtube.com/embed/w7ejDZ8SWv8', order: 1 },
      { title: 'React Fundamentals & JSX', duration: '24 min', videoUrl: 'https://www.youtube.com/embed/w7ejDZ8SWv8', order: 2 },
      { title: 'State & Props Deep Dive', duration: '32 min', videoUrl: 'https://www.youtube.com/embed/w7ejDZ8SWv8', order: 3 },
      { title: 'useState & useEffect', duration: '28 min', videoUrl: 'https://www.youtube.com/embed/w7ejDZ8SWv8', order: 4 },
      { title: 'Custom Hooks', duration: '22 min', videoUrl: 'https://www.youtube.com/embed/w7ejDZ8SWv8', order: 5 },
      { title: 'Context API & Global State', duration: '30 min', videoUrl: 'https://www.youtube.com/embed/w7ejDZ8SWv8', order: 6 },
      { title: 'Redux Toolkit', duration: '45 min', videoUrl: 'https://www.youtube.com/embed/w7ejDZ8SWv8', order: 7 },
      { title: 'React Router v6', duration: '26 min', videoUrl: 'https://www.youtube.com/embed/w7ejDZ8SWv8', order: 8 },
      { title: 'Project: E-Commerce App', duration: '90 min', videoUrl: 'https://www.youtube.com/embed/w7ejDZ8SWv8', order: 9 },
      { title: 'Performance Optimization', duration: '35 min', videoUrl: 'https://www.youtube.com/embed/w7ejDZ8SWv8', order: 10 },
    ],
  },
  {
    title: 'Python for Data Science & ML',
    description: 'Comprehensive Python course covering NumPy, Pandas, Matplotlib, Scikit-learn, and TensorFlow. Build real ML models and deploy them to production.',
    shortDescription: 'From Python basics to deploying real machine learning models.',
    instructor: 'Dr. Arjun Patel',
    instructorBio: 'PhD in Machine Learning, ex-Research Scientist at DeepMind.',
    category: 'Data Science',
    level: 'Beginner',
    duration: '60 hours',
    price: 94.99,
    isFree: false,
    thumbnail: 'https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=800&q=80',
    previewVideoUrl: 'https://www.youtube.com/embed/rfscVS0vtbw',
    rating: 4.8,
    reviewCount: 3201,
    enrolledCount: 24100,
    tags: ['Python', 'Machine Learning', 'Data Science', 'TensorFlow'],
    lessons: [
      { title: 'Python Basics & Setup', duration: '20 min', videoUrl: 'https://www.youtube.com/embed/rfscVS0vtbw', order: 1 },
      { title: 'NumPy Arrays & Operations', duration: '35 min', videoUrl: 'https://www.youtube.com/embed/rfscVS0vtbw', order: 2 },
      { title: 'Pandas DataFrames', duration: '40 min', videoUrl: 'https://www.youtube.com/embed/rfscVS0vtbw', order: 3 },
      { title: 'Data Visualization', duration: '30 min', videoUrl: 'https://www.youtube.com/embed/rfscVS0vtbw', order: 4 },
      { title: 'Machine Learning Basics', duration: '45 min', videoUrl: 'https://www.youtube.com/embed/rfscVS0vtbw', order: 5 },
      { title: 'Linear & Logistic Regression', duration: '50 min', videoUrl: 'https://www.youtube.com/embed/rfscVS0vtbw', order: 6 },
      { title: 'Decision Trees & Random Forest', duration: '42 min', videoUrl: 'https://www.youtube.com/embed/rfscVS0vtbw', order: 7 },
      { title: 'Neural Networks with TensorFlow', duration: '55 min', videoUrl: 'https://www.youtube.com/embed/rfscVS0vtbw', order: 8 },
    ],
  },
  {
    title: 'Node.js Backend Mastery',
    description: 'Build production-grade REST APIs and GraphQL services with Node.js, Express, MongoDB, and Redis. Includes authentication, caching, testing, and Docker deployment.',
    shortDescription: 'Build scalable REST APIs with Node.js, Express, and MongoDB.',
    instructor: 'Marcus Williams',
    instructorBio: 'Staff Backend Engineer with 12 years building Node.js systems at scale.',
    category: 'Web Development',
    level: 'Intermediate',
    duration: '42 hours',
    price: 79.99,
    isFree: false,
    thumbnail: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&q=80',
    previewVideoUrl: 'https://www.youtube.com/embed/fBNz5xF-Kx4',
    rating: 4.8,
    reviewCount: 1987,
    enrolledCount: 12300,
    tags: ['Node.js', 'Express', 'MongoDB', 'REST API'],
    lessons: [
      { title: 'Node.js Architecture', duration: '18 min', videoUrl: 'https://www.youtube.com/embed/fBNz5xF-Kx4', order: 1 },
      { title: 'Express Routing & Middleware', duration: '30 min', videoUrl: 'https://www.youtube.com/embed/fBNz5xF-Kx4', order: 2 },
      { title: 'MongoDB & Mongoose', duration: '38 min', videoUrl: 'https://www.youtube.com/embed/fBNz5xF-Kx4', order: 3 },
      { title: 'JWT Authentication', duration: '28 min', videoUrl: 'https://www.youtube.com/embed/fBNz5xF-Kx4', order: 4 },
      { title: 'File Uploads with Multer', duration: '22 min', videoUrl: 'https://www.youtube.com/embed/fBNz5xF-Kx4', order: 5 },
      { title: 'Redis Caching', duration: '35 min', videoUrl: 'https://www.youtube.com/embed/fBNz5xF-Kx4', order: 6 },
      { title: 'Testing with Jest', duration: '40 min', videoUrl: 'https://www.youtube.com/embed/fBNz5xF-Kx4', order: 7 },
      { title: 'Docker & Deployment', duration: '45 min', videoUrl: 'https://www.youtube.com/embed/fBNz5xF-Kx4', order: 8 },
    ],
  },
  {
    title: 'Deep Learning with PyTorch',
    description: 'Go from zero to hero in deep learning. Covers CNNs, RNNs, Transformers, GANs, and fine-tuning large language models with PyTorch.',
    shortDescription: 'Build CNNs, Transformers, and LLMs from scratch with PyTorch.',
    instructor: 'Dr. Priya Sharma',
    instructorBio: 'AI Research Scientist, published 20+ papers on deep learning architectures.',
    category: 'AI & Machine Learning',
    level: 'Advanced',
    duration: '70 hours',
    price: 109.99,
    isFree: false,
    thumbnail: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&q=80',
    previewVideoUrl: 'https://www.youtube.com/embed/c36lUUr864M',
    rating: 4.9,
    reviewCount: 1543,
    enrolledCount: 9800,
    tags: ['PyTorch', 'Deep Learning', 'AI', 'NLP', 'Computer Vision'],
    lessons: [
      { title: 'Tensors & Autograd', duration: '25 min', videoUrl: 'https://www.youtube.com/embed/c36lUUr864M', order: 1 },
      { title: 'Neural Network Basics', duration: '40 min', videoUrl: 'https://www.youtube.com/embed/c36lUUr864M', order: 2 },
      { title: 'CNNs for Image Classification', duration: '55 min', videoUrl: 'https://www.youtube.com/embed/c36lUUr864M', order: 3 },
      { title: 'RNNs & LSTMs', duration: '48 min', videoUrl: 'https://www.youtube.com/embed/c36lUUr864M', order: 4 },
      { title: 'Attention Mechanism', duration: '50 min', videoUrl: 'https://www.youtube.com/embed/c36lUUr864M', order: 5 },
      { title: 'Transformer Architecture', duration: '60 min', videoUrl: 'https://www.youtube.com/embed/c36lUUr864M', order: 6 },
      { title: 'Fine-tuning LLMs', duration: '65 min', videoUrl: 'https://www.youtube.com/embed/c36lUUr864M', order: 7 },
      { title: 'GANs & Diffusion Models', duration: '70 min', videoUrl: 'https://www.youtube.com/embed/c36lUUr864M', order: 8 },
    ],
  },
  {
    title: 'Flutter Mobile App Development',
    description: 'Build beautiful cross-platform iOS and Android apps with Flutter and Dart. Create 6 complete apps including a social media clone and e-wallet.',
    shortDescription: 'Build iOS & Android apps with Flutter — 6 real projects.',
    instructor: 'James Okonkwo',
    instructorBio: 'Google Developer Expert in Flutter with 8 years mobile development experience.',
    category: 'Mobile Development',
    level: 'Beginner',
    duration: '50 hours',
    price: 84.99,
    isFree: false,
    thumbnail: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&q=80',
    previewVideoUrl: 'https://www.youtube.com/embed/1ukSR1GRtMU',
    rating: 4.7,
    reviewCount: 2100,
    enrolledCount: 15600,
    tags: ['Flutter', 'Dart', 'Mobile', 'iOS', 'Android'],
    lessons: [
      { title: 'Dart Language Fundamentals', duration: '30 min', videoUrl: 'https://www.youtube.com/embed/1ukSR1GRtMU', order: 1 },
      { title: 'Flutter Widgets & Layouts', duration: '35 min', videoUrl: 'https://www.youtube.com/embed/1ukSR1GRtMU', order: 2 },
      { title: 'State Management (Provider)', duration: '40 min', videoUrl: 'https://www.youtube.com/embed/1ukSR1GRtMU', order: 3 },
      { title: 'Navigation & Routing', duration: '28 min', videoUrl: 'https://www.youtube.com/embed/1ukSR1GRtMU', order: 4 },
      { title: 'REST API Integration', duration: '38 min', videoUrl: 'https://www.youtube.com/embed/1ukSR1GRtMU', order: 5 },
      { title: 'Firebase Authentication', duration: '32 min', videoUrl: 'https://www.youtube.com/embed/1ukSR1GRtMU', order: 6 },
      { title: 'Project: Social Media App', duration: '85 min', videoUrl: 'https://www.youtube.com/embed/1ukSR1GRtMU', order: 7 },
      { title: 'Publishing to App Stores', duration: '25 min', videoUrl: 'https://www.youtube.com/embed/1ukSR1GRtMU', order: 8 },
    ],
  },
  {
    title: 'AWS Solutions Architect',
    description: 'Master AWS services and prepare for the Solutions Architect Associate certification. Covers EC2, S3, RDS, Lambda, VPC, IAM, CloudFormation, and more with hands-on labs.',
    shortDescription: 'Master AWS and pass the Solutions Architect certification exam.',
    instructor: 'Rahul Gupta',
    instructorBio: 'AWS Certified Solutions Architect Professional with 10+ years cloud experience.',
    category: 'DevOps & Cloud',
    level: 'Intermediate',
    duration: '55 hours',
    price: 99.99,
    isFree: false,
    thumbnail: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&q=80',
    previewVideoUrl: 'https://www.youtube.com/embed/3hLmDS179YE',
    rating: 4.8,
    reviewCount: 3400,
    enrolledCount: 21000,
    tags: ['AWS', 'Cloud', 'DevOps', 'Certification'],
    lessons: [
      { title: 'AWS Global Infrastructure', duration: '20 min', videoUrl: 'https://www.youtube.com/embed/3hLmDS179YE', order: 1 },
      { title: 'EC2 & Auto Scaling', duration: '42 min', videoUrl: 'https://www.youtube.com/embed/3hLmDS179YE', order: 2 },
      { title: 'S3 & CloudFront', duration: '35 min', videoUrl: 'https://www.youtube.com/embed/3hLmDS179YE', order: 3 },
      { title: 'RDS & DynamoDB', duration: '38 min', videoUrl: 'https://www.youtube.com/embed/3hLmDS179YE', order: 4 },
      { title: 'VPC & Networking', duration: '45 min', videoUrl: 'https://www.youtube.com/embed/3hLmDS179YE', order: 5 },
      { title: 'IAM & Security', duration: '32 min', videoUrl: 'https://www.youtube.com/embed/3hLmDS179YE', order: 6 },
      { title: 'Lambda & Serverless', duration: '40 min', videoUrl: 'https://www.youtube.com/embed/3hLmDS179YE', order: 7 },
      { title: 'CloudFormation & CDK', duration: '50 min', videoUrl: 'https://www.youtube.com/embed/3hLmDS179YE', order: 8 },
    ],
  },
  {
    title: 'Ethical Hacking & Penetration Testing',
    description: 'Learn cybersecurity from the attacker\'s perspective. Master reconnaissance, exploitation, privilege escalation, and post-exploitation in legal, ethical environments.',
    shortDescription: 'Become an ethical hacker — reconnaissance to full exploitation.',
    instructor: 'Alex Mercer',
    instructorBio: 'CEH & OSCP certified security researcher with 8 years in red-teaming.',
    category: 'Cybersecurity',
    level: 'Intermediate',
    duration: '65 hours',
    price: 94.99,
    isFree: false,
    thumbnail: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&q=80',
    previewVideoUrl: 'https://www.youtube.com/embed/3Kq1MIfTWCE',
    rating: 4.7,
    reviewCount: 1876,
    enrolledCount: 11200,
    tags: ['Cybersecurity', 'Ethical Hacking', 'Penetration Testing', 'Kali Linux'],
    lessons: [
      { title: 'Ethical Hacking Intro & Legal', duration: '15 min', videoUrl: 'https://www.youtube.com/embed/3Kq1MIfTWCE', order: 1 },
      { title: 'Reconnaissance & OSINT', duration: '40 min', videoUrl: 'https://www.youtube.com/embed/3Kq1MIfTWCE', order: 2 },
      { title: 'Network Scanning & Enumeration', duration: '35 min', videoUrl: 'https://www.youtube.com/embed/3Kq1MIfTWCE', order: 3 },
      { title: 'Vulnerability Assessment', duration: '30 min', videoUrl: 'https://www.youtube.com/embed/3Kq1MIfTWCE', order: 4 },
      { title: 'Exploitation with Metasploit', duration: '50 min', videoUrl: 'https://www.youtube.com/embed/3Kq1MIfTWCE', order: 5 },
      { title: 'Web App Attacks (SQLi, XSS)', duration: '45 min', videoUrl: 'https://www.youtube.com/embed/3Kq1MIfTWCE', order: 6 },
      { title: 'Privilege Escalation', duration: '40 min', videoUrl: 'https://www.youtube.com/embed/3Kq1MIfTWCE', order: 7 },
      { title: 'Reporting & Remediation', duration: '25 min', videoUrl: 'https://www.youtube.com/embed/3Kq1MIfTWCE', order: 8 },
    ],
  },
  {
    title: 'UI/UX Design Mastery with Figma',
    description: 'Learn professional UI/UX design using Figma. Covers design thinking, user research, wireframing, prototyping, design systems, and building a portfolio-ready case study.',
    shortDescription: 'Design stunning UIs and build a complete design portfolio in Figma.',
    instructor: 'Sofia Andersen',
    instructorBio: 'Lead UX Designer at Airbnb, formerly at Apple and Spotify.',
    category: 'UI/UX Design',
    level: 'Beginner',
    duration: '38 hours',
    price: 74.99,
    isFree: false,
    thumbnail: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&q=80',
    previewVideoUrl: 'https://www.youtube.com/embed/FTFaQWZBqQ8',
    rating: 4.9,
    reviewCount: 4100,
    enrolledCount: 28700,
    tags: ['Figma', 'UI Design', 'UX Design', 'Prototyping'],
    lessons: [
      { title: 'Design Thinking & Process', duration: '25 min', videoUrl: 'https://www.youtube.com/embed/FTFaQWZBqQ8', order: 1 },
      { title: 'User Research & Personas', duration: '30 min', videoUrl: 'https://www.youtube.com/embed/FTFaQWZBqQ8', order: 2 },
      { title: 'Figma Interface & Tools', duration: '22 min', videoUrl: 'https://www.youtube.com/embed/FTFaQWZBqQ8', order: 3 },
      { title: 'Typography & Color Theory', duration: '28 min', videoUrl: 'https://www.youtube.com/embed/FTFaQWZBqQ8', order: 4 },
      { title: 'Wireframing & Low-fi Prototypes', duration: '35 min', videoUrl: 'https://www.youtube.com/embed/FTFaQWZBqQ8', order: 5 },
      { title: 'High-Fidelity UI Design', duration: '55 min', videoUrl: 'https://www.youtube.com/embed/FTFaQWZBqQ8', order: 6 },
      { title: 'Design Systems & Components', duration: '45 min', videoUrl: 'https://www.youtube.com/embed/FTFaQWZBqQ8', order: 7 },
      { title: 'Portfolio Case Study', duration: '60 min', videoUrl: 'https://www.youtube.com/embed/FTFaQWZBqQ8', order: 8 },
    ],
  },
  {
    title: 'Full Stack Web Development Bootcamp',
    description: 'The most complete web development course. HTML, CSS, JavaScript, React, Node.js, MongoDB, SQL, and deployment. Build 10 projects and land your first developer job.',
    shortDescription: 'Zero to hired — the most complete full-stack web dev course.',
    instructor: 'Emma Rodriguez',
    instructorBio: 'Full-stack developer, bootcamp instructor, and hiring manager with 300+ graduates placed.',
    category: 'Web Development',
    level: 'Beginner',
    duration: '100 hours',
    price: 119.99,
    isFree: false,
    thumbnail: 'https://images.unsplash.com/photo-1547658719-da2b51169166?w=800&q=80',
    previewVideoUrl: 'https://www.youtube.com/embed/nu_pCVPKzTk',
    rating: 4.8,
    reviewCount: 6800,
    enrolledCount: 45000,
    tags: ['HTML', 'CSS', 'JavaScript', 'React', 'Node.js', 'Full Stack'],
    lessons: [
      { title: 'HTML5 & Semantic Markup', duration: '30 min', videoUrl: 'https://www.youtube.com/embed/nu_pCVPKzTk', order: 1 },
      { title: 'CSS3 & Flexbox/Grid', duration: '45 min', videoUrl: 'https://www.youtube.com/embed/nu_pCVPKzTk', order: 2 },
      { title: 'JavaScript ES6+', duration: '60 min', videoUrl: 'https://www.youtube.com/embed/nu_pCVPKzTk', order: 3 },
      { title: 'DOM Manipulation', duration: '35 min', videoUrl: 'https://www.youtube.com/embed/nu_pCVPKzTk', order: 4 },
      { title: 'React Fundamentals', duration: '50 min', videoUrl: 'https://www.youtube.com/embed/nu_pCVPKzTk', order: 5 },
      { title: 'Node.js & Express APIs', duration: '55 min', videoUrl: 'https://www.youtube.com/embed/nu_pCVPKzTk', order: 6 },
      { title: 'MongoDB & SQL Databases', duration: '48 min', videoUrl: 'https://www.youtube.com/embed/nu_pCVPKzTk', order: 7 },
      { title: 'Git, GitHub & Deployment', duration: '30 min', videoUrl: 'https://www.youtube.com/embed/nu_pCVPKzTk', order: 8 },
    ],
  },
  {
    title: 'TypeScript for React Developers',
    description: 'Supercharge your React apps with TypeScript. Learn type safety, interfaces, generics, and advanced patterns. Migrate an existing React project to TypeScript end to end.',
    shortDescription: 'Add TypeScript to your React projects — from basics to advanced.',
    instructor: 'David Kim',
    instructorBio: 'TypeScript contributor and senior frontend engineer at Microsoft.',
    category: 'Web Development',
    level: 'Intermediate',
    duration: '28 hours',
    price: 69.99,
    isFree: false,
    thumbnail: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&q=80',
    previewVideoUrl: 'https://www.youtube.com/embed/BwuLxPH8IDs',
    rating: 4.8,
    reviewCount: 1340,
    enrolledCount: 8900,
    tags: ['TypeScript', 'React', 'JavaScript', 'Frontend'],
    lessons: [
      { title: 'TypeScript Basics & Setup', duration: '20 min', videoUrl: 'https://www.youtube.com/embed/BwuLxPH8IDs', order: 1 },
      { title: 'Types, Interfaces & Enums', duration: '35 min', videoUrl: 'https://www.youtube.com/embed/BwuLxPH8IDs', order: 2 },
      { title: 'Generics', duration: '30 min', videoUrl: 'https://www.youtube.com/embed/BwuLxPH8IDs', order: 3 },
      { title: 'React + TypeScript Props', duration: '28 min', videoUrl: 'https://www.youtube.com/embed/BwuLxPH8IDs', order: 4 },
      { title: 'Typing Hooks & Contexts', duration: '32 min', videoUrl: 'https://www.youtube.com/embed/BwuLxPH8IDs', order: 5 },
      { title: 'API Calls with Types', duration: '25 min', videoUrl: 'https://www.youtube.com/embed/BwuLxPH8IDs', order: 6 },
      { title: 'Migration Walkthrough', duration: '55 min', videoUrl: 'https://www.youtube.com/embed/BwuLxPH8IDs', order: 7 },
    ],
  },
  {
    title: 'Kubernetes for Developers',
    description: 'Learn container orchestration with Kubernetes. Deploy, scale, and manage containerized applications. Covers Pods, Services, Deployments, Helm, and CI/CD integration.',
    shortDescription: 'Deploy and scale apps with Kubernetes — from zero to production.',
    instructor: 'Nina Petrov',
    instructorBio: 'CNCF Ambassador and Kubernetes contributor with 7 years DevOps experience.',
    category: 'DevOps & Cloud',
    level: 'Advanced',
    duration: '40 hours',
    price: 89.99,
    isFree: false,
    thumbnail: 'https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=800&q=80',
    previewVideoUrl: 'https://www.youtube.com/embed/s_o8dwzRlu4',
    rating: 4.7,
    reviewCount: 980,
    enrolledCount: 6700,
    tags: ['Kubernetes', 'Docker', 'DevOps', 'Cloud Native', 'Helm'],
    lessons: [
      { title: 'Container & Docker Refresher', duration: '25 min', videoUrl: 'https://www.youtube.com/embed/s_o8dwzRlu4', order: 1 },
      { title: 'Kubernetes Architecture', duration: '30 min', videoUrl: 'https://www.youtube.com/embed/s_o8dwzRlu4', order: 2 },
      { title: 'Pods, Deployments & Services', duration: '40 min', videoUrl: 'https://www.youtube.com/embed/s_o8dwzRlu4', order: 3 },
      { title: 'ConfigMaps & Secrets', duration: '25 min', videoUrl: 'https://www.youtube.com/embed/s_o8dwzRlu4', order: 4 },
      { title: 'Ingress & Networking', duration: '35 min', videoUrl: 'https://www.youtube.com/embed/s_o8dwzRlu4', order: 5 },
      { title: 'Helm Charts', duration: '38 min', videoUrl: 'https://www.youtube.com/embed/s_o8dwzRlu4', order: 6 },
      { title: 'CI/CD with GitHub Actions', duration: '45 min', videoUrl: 'https://www.youtube.com/embed/s_o8dwzRlu4', order: 7 },
    ],
  },
  {
    title: 'SQL & Database Design',
    description: 'Learn SQL from absolute beginner to advanced. Covers SELECT queries, JOINs, subqueries, window functions, indexing, and database normalization with PostgreSQL.',
    shortDescription: 'Master SQL and database design from scratch with PostgreSQL.',
    instructor: 'Chen Wei',
    instructorBio: 'Database architect with 15 years designing systems at Fortune 500 companies.',
    category: 'Database',
    level: 'Beginner',
    duration: '30 hours',
    price: 0,
    isFree: true,
    thumbnail: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=800&q=80',
    previewVideoUrl: 'https://www.youtube.com/embed/HXV3zeQKqGY',
    rating: 4.6,
    reviewCount: 5200,
    enrolledCount: 38000,
    tags: ['SQL', 'PostgreSQL', 'Database', 'Data'],
    lessons: [
      { title: 'What is a Database?', duration: '12 min', videoUrl: 'https://www.youtube.com/embed/HXV3zeQKqGY', order: 1 },
      { title: 'SELECT & WHERE', duration: '25 min', videoUrl: 'https://www.youtube.com/embed/HXV3zeQKqGY', order: 2 },
      { title: 'JOINs & Relationships', duration: '35 min', videoUrl: 'https://www.youtube.com/embed/HXV3zeQKqGY', order: 3 },
      { title: 'Aggregations & GROUP BY', duration: '28 min', videoUrl: 'https://www.youtube.com/embed/HXV3zeQKqGY', order: 4 },
      { title: 'Subqueries & CTEs', duration: '30 min', videoUrl: 'https://www.youtube.com/embed/HXV3zeQKqGY', order: 5 },
      { title: 'Window Functions', duration: '32 min', videoUrl: 'https://www.youtube.com/embed/HXV3zeQKqGY', order: 6 },
      { title: 'Indexing & Performance', duration: '35 min', videoUrl: 'https://www.youtube.com/embed/HXV3zeQKqGY', order: 7 },
      { title: 'Database Normalization', duration: '30 min', videoUrl: 'https://www.youtube.com/embed/HXV3zeQKqGY', order: 8 },
    ],
  },
  {
    title: 'Digital Marketing & SEO Masterclass',
    description: 'Learn digital marketing from top to bottom — SEO, SEM, social media marketing, email campaigns, Google Analytics 4, and growth hacking strategies that actually work.',
    shortDescription: 'Master SEO, social media, and paid ads to grow any business online.',
    instructor: 'Lena Fischer',
    instructorBio: 'Growth marketer who scaled 3 startups to $10M+ ARR.',
    category: 'Digital Marketing',
    level: 'Beginner',
    duration: '32 hours',
    price: 64.99,
    isFree: false,
    thumbnail: 'https://images.unsplash.com/photo-1432888622747-4eb9a8efeb07?w=800&q=80',
    previewVideoUrl: 'https://www.youtube.com/embed/1Be4mEjXEE0',
    rating: 4.6,
    reviewCount: 2800,
    enrolledCount: 19000,
    tags: ['SEO', 'Digital Marketing', 'Google Ads', 'Social Media'],
    lessons: [
      { title: 'Digital Marketing Overview', duration: '15 min', videoUrl: 'https://www.youtube.com/embed/1Be4mEjXEE0', order: 1 },
      { title: 'SEO Fundamentals', duration: '40 min', videoUrl: 'https://www.youtube.com/embed/1Be4mEjXEE0', order: 2 },
      { title: 'On-Page & Technical SEO', duration: '38 min', videoUrl: 'https://www.youtube.com/embed/1Be4mEjXEE0', order: 3 },
      { title: 'Google Ads & PPC', duration: '42 min', videoUrl: 'https://www.youtube.com/embed/1Be4mEjXEE0', order: 4 },
      { title: 'Social Media Marketing', duration: '35 min', videoUrl: 'https://www.youtube.com/embed/1Be4mEjXEE0', order: 5 },
      { title: 'Email Marketing', duration: '28 min', videoUrl: 'https://www.youtube.com/embed/1Be4mEjXEE0', order: 6 },
      { title: 'Google Analytics 4', duration: '35 min', videoUrl: 'https://www.youtube.com/embed/1Be4mEjXEE0', order: 7 },
      { title: 'Growth Hacking Strategies', duration: '40 min', videoUrl: 'https://www.youtube.com/embed/1Be4mEjXEE0', order: 8 },
    ],
  },
  {
    title: 'React Native: Mobile Apps with JavaScript',
    description: 'Build production-ready iOS and Android apps with React Native and Expo. Learn navigation, animations, device APIs, state management, and deployment to app stores.',
    shortDescription: 'Build iOS & Android apps with React Native and Expo.',
    instructor: 'Carlos Mendes',
    instructorBio: 'React Native core contributor and mobile lead at Meta.',
    category: 'Mobile Development',
    level: 'Intermediate',
    duration: '44 hours',
    price: 84.99,
    isFree: false,
    thumbnail: 'https://images.unsplash.com/photo-1607252650355-f7fd0460ccdb?w=800&q=80',
    previewVideoUrl: 'https://www.youtube.com/embed/0-S5a0eXPoc',
    rating: 4.7,
    reviewCount: 1650,
    enrolledCount: 11400,
    tags: ['React Native', 'JavaScript', 'Mobile', 'Expo'],
    lessons: [
      { title: 'Expo Setup & First App', duration: '18 min', videoUrl: 'https://www.youtube.com/embed/0-S5a0eXPoc', order: 1 },
      { title: 'Core Components & Styling', duration: '30 min', videoUrl: 'https://www.youtube.com/embed/0-S5a0eXPoc', order: 2 },
      { title: 'Navigation with React Nav', duration: '35 min', videoUrl: 'https://www.youtube.com/embed/0-S5a0eXPoc', order: 3 },
      { title: 'Animations & Gestures', duration: '40 min', videoUrl: 'https://www.youtube.com/embed/0-S5a0eXPoc', order: 4 },
      { title: 'Camera & Location APIs', duration: '32 min', videoUrl: 'https://www.youtube.com/embed/0-S5a0eXPoc', order: 5 },
      { title: 'Redux in React Native', duration: '38 min', videoUrl: 'https://www.youtube.com/embed/0-S5a0eXPoc', order: 6 },
      { title: 'Publishing to Stores', duration: '25 min', videoUrl: 'https://www.youtube.com/embed/0-S5a0eXPoc', order: 7 },
    ],
  },
  {
    title: 'Machine Learning Engineering',
    description: 'Bridge the gap between data science and production ML. Learn MLOps, model serving, feature stores, A/B testing, monitoring, and building end-to-end ML pipelines.',
    shortDescription: 'Deploy and scale ML models in production — MLOps from scratch.',
    instructor: 'Dr. Yuki Tanaka',
    instructorBio: 'ML Engineer at Uber, building production ML systems serving 100M+ predictions/day.',
    category: 'AI & Machine Learning',
    level: 'Advanced',
    duration: '55 hours',
    price: 109.99,
    isFree: false,
    thumbnail: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&q=80',
    previewVideoUrl: 'https://www.youtube.com/embed/aircAruvnKk',
    rating: 4.8,
    reviewCount: 876,
    enrolledCount: 5400,
    tags: ['MLOps', 'Machine Learning', 'Python', 'Production AI'],
    lessons: [
      { title: 'ML in Production Overview', duration: '20 min', videoUrl: 'https://www.youtube.com/embed/aircAruvnKk', order: 1 },
      { title: 'Feature Engineering at Scale', duration: '45 min', videoUrl: 'https://www.youtube.com/embed/aircAruvnKk', order: 2 },
      { title: 'Model Training Pipelines', duration: '50 min', videoUrl: 'https://www.youtube.com/embed/aircAruvnKk', order: 3 },
      { title: 'Model Serving with FastAPI', duration: '40 min', videoUrl: 'https://www.youtube.com/embed/aircAruvnKk', order: 4 },
      { title: 'A/B Testing & Experimentation', duration: '35 min', videoUrl: 'https://www.youtube.com/embed/aircAruvnKk', order: 5 },
      { title: 'Model Monitoring & Drift', duration: '38 min', videoUrl: 'https://www.youtube.com/embed/aircAruvnKk', order: 6 },
      { title: 'CI/CD for ML', duration: '42 min', videoUrl: 'https://www.youtube.com/embed/aircAruvnKk', order: 7 },
    ],
  },
  {
    title: 'JavaScript: The Complete Guide',
    description: 'Master JavaScript from the very basics to advanced concepts including closures, prototypes, async/await, the event loop, and modern ES2023 features.',
    shortDescription: 'Master JavaScript — from zero to advanced with real projects.',
    instructor: 'Ryan Taylor',
    instructorBio: 'V8 JavaScript engine contributor and JavaScript educator with 1M+ students.',
    category: 'Web Development',
    level: 'Beginner',
    duration: '52 hours',
    price: 0,
    isFree: true,
    thumbnail: 'https://images.unsplash.com/photo-1579468118864-1b9ea3c0db4a?w=800&q=80',
    previewVideoUrl: 'https://www.youtube.com/embed/PkZNo7MFNFg',
    rating: 4.9,
    reviewCount: 9800,
    enrolledCount: 72000,
    tags: ['JavaScript', 'ES6', 'Web Development', 'Programming'],
    lessons: [
      { title: 'Variables & Data Types', duration: '25 min', videoUrl: 'https://www.youtube.com/embed/PkZNo7MFNFg', order: 1 },
      { title: 'Functions & Scope', duration: '32 min', videoUrl: 'https://www.youtube.com/embed/PkZNo7MFNFg', order: 2 },
      { title: 'Arrays & Objects', duration: '35 min', videoUrl: 'https://www.youtube.com/embed/PkZNo7MFNFg', order: 3 },
      { title: 'Closures & HOF', duration: '30 min', videoUrl: 'https://www.youtube.com/embed/PkZNo7MFNFg', order: 4 },
      { title: 'Promises & Async/Await', duration: '38 min', videoUrl: 'https://www.youtube.com/embed/PkZNo7MFNFg', order: 5 },
      { title: 'The Event Loop', duration: '28 min', videoUrl: 'https://www.youtube.com/embed/PkZNo7MFNFg', order: 6 },
      { title: 'Classes & Prototypes', duration: '32 min', videoUrl: 'https://www.youtube.com/embed/PkZNo7MFNFg', order: 7 },
      { title: 'Modern JS (ES2023)', duration: '35 min', videoUrl: 'https://www.youtube.com/embed/PkZNo7MFNFg', order: 8 },
    ],
  },
  {
    title: 'GraphQL API Development',
    description: 'Build efficient, flexible APIs with GraphQL. Learn schema design, resolvers, mutations, subscriptions, Apollo Server, and connecting to React on the frontend.',
    shortDescription: 'Build and consume GraphQL APIs with Apollo — full stack.',
    instructor: 'Aisha Johnson',
    instructorBio: 'GraphQL Foundation member and API architect at Shopify.',
    category: 'Web Development',
    level: 'Intermediate',
    duration: '35 hours',
    price: 79.99,
    isFree: false,
    thumbnail: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80',
    previewVideoUrl: 'https://www.youtube.com/embed/ed8SzALpx1Q',
    rating: 4.7,
    reviewCount: 1120,
    enrolledCount: 7800,
    tags: ['GraphQL', 'Apollo', 'API', 'Node.js', 'React'],
    lessons: [
      { title: 'REST vs GraphQL', duration: '18 min', videoUrl: 'https://www.youtube.com/embed/ed8SzALpx1Q', order: 1 },
      { title: 'Schema & Type Definitions', duration: '30 min', videoUrl: 'https://www.youtube.com/embed/ed8SzALpx1Q', order: 2 },
      { title: 'Queries & Resolvers', duration: '35 min', videoUrl: 'https://www.youtube.com/embed/ed8SzALpx1Q', order: 3 },
      { title: 'Mutations', duration: '28 min', videoUrl: 'https://www.youtube.com/embed/ed8SzALpx1Q', order: 4 },
      { title: 'Authentication in GraphQL', duration: '32 min', videoUrl: 'https://www.youtube.com/embed/ed8SzALpx1Q', order: 5 },
      { title: 'Subscriptions (WebSockets)', duration: '38 min', videoUrl: 'https://www.youtube.com/embed/ed8SzALpx1Q', order: 6 },
      { title: 'Apollo Client in React', duration: '45 min', videoUrl: 'https://www.youtube.com/embed/ed8SzALpx1Q', order: 7 },
    ],
  },
  {
    title: 'Data Structures & Algorithms in Python',
    description: 'Crack coding interviews at FAANG companies. Master arrays, linked lists, trees, graphs, dynamic programming, and sorting algorithms with 200+ practice problems.',
    shortDescription: 'Crack FAANG interviews — 200+ DSA problems solved in Python.',
    instructor: 'Kevin Park',
    instructorBio: 'Former Google and Amazon SWE, now coaching engineers to land dream jobs.',
    category: 'Data Science',
    level: 'Intermediate',
    duration: '50 hours',
    price: 89.99,
    isFree: false,
    thumbnail: 'https://images.unsplash.com/photo-1516116216624-53e697fedbea?w=800&q=80',
    previewVideoUrl: 'https://www.youtube.com/embed/pkYVOmU3MgA',
    rating: 4.9,
    reviewCount: 4300,
    enrolledCount: 31000,
    tags: ['DSA', 'Python', 'Algorithms', 'Interview Prep', 'LeetCode'],
    lessons: [
      { title: 'Big O Notation', duration: '20 min', videoUrl: 'https://www.youtube.com/embed/pkYVOmU3MgA', order: 1 },
      { title: 'Arrays & Strings', duration: '40 min', videoUrl: 'https://www.youtube.com/embed/pkYVOmU3MgA', order: 2 },
      { title: 'Linked Lists', duration: '38 min', videoUrl: 'https://www.youtube.com/embed/pkYVOmU3MgA', order: 3 },
      { title: 'Stacks & Queues', duration: '32 min', videoUrl: 'https://www.youtube.com/embed/pkYVOmU3MgA', order: 4 },
      { title: 'Trees & BSTs', duration: '45 min', videoUrl: 'https://www.youtube.com/embed/pkYVOmU3MgA', order: 5 },
      { title: 'Graphs & BFS/DFS', duration: '50 min', videoUrl: 'https://www.youtube.com/embed/pkYVOmU3MgA', order: 6 },
      { title: 'Dynamic Programming', duration: '60 min', videoUrl: 'https://www.youtube.com/embed/pkYVOmU3MgA', order: 7 },
      { title: 'System Design Basics', duration: '45 min', videoUrl: 'https://www.youtube.com/embed/pkYVOmU3MgA', order: 8 },
    ],
  },
  {
    title: 'MongoDB: The Complete Guide',
    description: 'Learn MongoDB from installation to advanced aggregation pipelines. Covers schema design, indexing, replication, sharding, Atlas, and performance tuning.',
    shortDescription: 'Master MongoDB — from basics to advanced aggregations and Atlas.',
    instructor: 'Omar Abdullah',
    instructorBio: 'MongoDB Atlas engineer and open-source contributor.',
    category: 'Database',
    level: 'Intermediate',
    duration: '28 hours',
    price: 69.99,
    isFree: false,
    thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80',
    previewVideoUrl: 'https://www.youtube.com/embed/-bt_y4Loofg',
    rating: 4.6,
    reviewCount: 1100,
    enrolledCount: 8100,
    tags: ['MongoDB', 'NoSQL', 'Database', 'Atlas'],
    lessons: [
      { title: 'MongoDB vs SQL', duration: '15 min', videoUrl: 'https://www.youtube.com/embed/-bt_y4Loofg', order: 1 },
      { title: 'CRUD Operations', duration: '30 min', videoUrl: 'https://www.youtube.com/embed/-bt_y4Loofg', order: 2 },
      { title: 'Schema Design Patterns', duration: '35 min', videoUrl: 'https://www.youtube.com/embed/-bt_y4Loofg', order: 3 },
      { title: 'Indexing & Query Perf', duration: '32 min', videoUrl: 'https://www.youtube.com/embed/-bt_y4Loofg', order: 4 },
      { title: 'Aggregation Pipeline', duration: '45 min', videoUrl: 'https://www.youtube.com/embed/-bt_y4Loofg', order: 5 },
      { title: 'Transactions', duration: '28 min', videoUrl: 'https://www.youtube.com/embed/-bt_y4Loofg', order: 6 },
      { title: 'Atlas & Deployment', duration: '35 min', videoUrl: 'https://www.youtube.com/embed/-bt_y4Loofg', order: 7 },
    ],
  },
  {
    title: 'Tailwind CSS Masterclass',
    description: 'Become a Tailwind CSS expert. Build stunning, responsive UIs faster than ever. Covers utility-first design, custom themes, plugins, animations, and dark mode.',
    shortDescription: 'Build stunning UIs faster with Tailwind CSS utility-first design.',
    instructor: 'Hannah Müller',
    instructorBio: 'Frontend architect and Tailwind CSS educator with 50k+ students.',
    category: 'UI/UX Design',
    level: 'Beginner',
    duration: '20 hours',
    price: 49.99,
    isFree: false,
    thumbnail: 'https://images.unsplash.com/photo-1587440871875-191322ee64b0?w=800&q=80',
    previewVideoUrl: 'https://www.youtube.com/embed/dFgzHOX84xQ',
    rating: 4.8,
    reviewCount: 3200,
    enrolledCount: 22000,
    tags: ['Tailwind CSS', 'CSS', 'Frontend', 'UI Design'],
    lessons: [
      { title: 'Utility-First CSS Philosophy', duration: '15 min', videoUrl: 'https://www.youtube.com/embed/dFgzHOX84xQ', order: 1 },
      { title: 'Layout with Flex & Grid', duration: '28 min', videoUrl: 'https://www.youtube.com/embed/dFgzHOX84xQ', order: 2 },
      { title: 'Responsive Design', duration: '25 min', videoUrl: 'https://www.youtube.com/embed/dFgzHOX84xQ', order: 3 },
      { title: 'Typography & Colors', duration: '20 min', videoUrl: 'https://www.youtube.com/embed/dFgzHOX84xQ', order: 4 },
      { title: 'Dark Mode', duration: '18 min', videoUrl: 'https://www.youtube.com/embed/dFgzHOX84xQ', order: 5 },
      { title: 'Custom Theme & Config', duration: '30 min', videoUrl: 'https://www.youtube.com/embed/dFgzHOX84xQ', order: 6 },
      { title: 'Animations & Transitions', duration: '22 min', videoUrl: 'https://www.youtube.com/embed/dFgzHOX84xQ', order: 7 },
      { title: 'Building a UI Component Lib', duration: '45 min', videoUrl: 'https://www.youtube.com/embed/dFgzHOX84xQ', order: 8 },
    ],
  },
  {
    title: 'Startup Finance & Fundraising',
    description: 'Learn how startups raise money from idea to Series A. Covers cap tables, term sheets, SAFE notes, valuations, pitching investors, and managing startup finances.',
    shortDescription: 'Raise funding for your startup — from bootstrapping to Series A.',
    instructor: 'Michael Osei',
    instructorBio: 'VC partner at Sequoia Capital, advisor to 50+ startups.',
    category: 'Business & Finance',
    level: 'Intermediate',
    duration: '25 hours',
    price: 74.99,
    isFree: false,
    thumbnail: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&q=80',
    previewVideoUrl: 'https://www.youtube.com/embed/7umck4lkspare',
    rating: 4.7,
    reviewCount: 1560,
    enrolledCount: 10200,
    tags: ['Startup', 'Finance', 'Fundraising', 'VC', 'Business'],
    lessons: [
      { title: 'Startup Funding Overview', duration: '20 min', videoUrl: 'https://www.youtube.com/embed/7umck4lkspare', order: 1 },
      { title: 'Pre-Seed & Bootstrapping', duration: '28 min', videoUrl: 'https://www.youtube.com/embed/7umck4lkspare', order: 2 },
      { title: 'SAFE Notes & Convertibles', duration: '32 min', videoUrl: 'https://www.youtube.com/embed/7umck4lkspare', order: 3 },
      { title: 'Cap Table Fundamentals', duration: '35 min', videoUrl: 'https://www.youtube.com/embed/7umck4lkspare', order: 4 },
      { title: 'Pitch Deck Masterclass', duration: '45 min', videoUrl: 'https://www.youtube.com/embed/7umck4lkspare', order: 5 },
      { title: 'Term Sheet Negotiation', duration: '38 min', videoUrl: 'https://www.youtube.com/embed/7umck4lkspare', order: 6 },
      { title: 'Series A Readiness', duration: '30 min', videoUrl: 'https://www.youtube.com/embed/7umck4lkspare', order: 7 },
    ],
  },
  {
    title: 'Next.js 14 Full Stack Development',
    description: 'Build production-ready full-stack apps with Next.js 14. Master App Router, Server Components, Server Actions, Prisma, NextAuth, and Vercel deployment.',
    shortDescription: 'Build full-stack apps with Next.js 14 App Router and Server Actions.',
    instructor: 'Lily Zhang',
    instructorBio: 'Next.js educator and Vercel community expert with 200k YouTube subscribers.',
    category: 'Web Development',
    level: 'Intermediate',
    duration: '45 hours',
    price: 94.99,
    isFree: false,
    thumbnail: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&q=80',
    previewVideoUrl: 'https://www.youtube.com/embed/wm5gMKuwSYk',
    rating: 4.9,
    reviewCount: 2870,
    enrolledCount: 19500,
    tags: ['Next.js', 'React', 'Full Stack', 'Vercel', 'Server Components'],
    lessons: [
      { title: 'Next.js vs React', duration: '15 min', videoUrl: 'https://www.youtube.com/embed/wm5gMKuwSYk', order: 1 },
      { title: 'App Router & File System', duration: '28 min', videoUrl: 'https://www.youtube.com/embed/wm5gMKuwSYk', order: 2 },
      { title: 'Server & Client Components', duration: '35 min', videoUrl: 'https://www.youtube.com/embed/wm5gMKuwSYk', order: 3 },
      { title: 'Server Actions & Forms', duration: '32 min', videoUrl: 'https://www.youtube.com/embed/wm5gMKuwSYk', order: 4 },
      { title: 'Data Fetching Patterns', duration: '38 min', videoUrl: 'https://www.youtube.com/embed/wm5gMKuwSYk', order: 5 },
      { title: 'Authentication with NextAuth', duration: '42 min', videoUrl: 'https://www.youtube.com/embed/wm5gMKuwSYk', order: 6 },
      { title: 'Prisma & Database', duration: '45 min', videoUrl: 'https://www.youtube.com/embed/wm5gMKuwSYk', order: 7 },
      { title: 'Deploy to Vercel', duration: '20 min', videoUrl: 'https://www.youtube.com/embed/wm5gMKuwSYk', order: 8 },
    ],
  },
  {
    title: 'Network Security Fundamentals',
    description: 'Master the foundations of network security. Firewalls, VPNs, IDS/IPS, TLS/SSL, zero-trust architecture, and preparing for CompTIA Security+ certification.',
    shortDescription: 'Master network security and prepare for Security+ certification.',
    instructor: 'Thomas Berg',
    instructorBio: 'CISSP certified network security engineer with 15 years in enterprise security.',
    category: 'Cybersecurity',
    level: 'Beginner',
    duration: '38 hours',
    price: 79.99,
    isFree: false,
    thumbnail: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&q=80',
    previewVideoUrl: 'https://www.youtube.com/embed/E03gh1huvW4',
    rating: 4.6,
    reviewCount: 980,
    enrolledCount: 7200,
    tags: ['Network Security', 'Cybersecurity', 'CompTIA', 'Firewalls'],
    lessons: [
      { title: 'Networking Basics Review', duration: '25 min', videoUrl: 'https://www.youtube.com/embed/E03gh1huvW4', order: 1 },
      { title: 'Threats & Attack Vectors', duration: '30 min', videoUrl: 'https://www.youtube.com/embed/E03gh1huvW4', order: 2 },
      { title: 'Firewalls & ACLs', duration: '35 min', videoUrl: 'https://www.youtube.com/embed/E03gh1huvW4', order: 3 },
      { title: 'VPNs & Tunneling', duration: '30 min', videoUrl: 'https://www.youtube.com/embed/E03gh1huvW4', order: 4 },
      { title: 'TLS/SSL & Encryption', duration: '38 min', videoUrl: 'https://www.youtube.com/embed/E03gh1huvW4', order: 5 },
      { title: 'IDS/IPS Systems', duration: '28 min', videoUrl: 'https://www.youtube.com/embed/E03gh1huvW4', order: 6 },
      { title: 'Zero Trust Architecture', duration: '32 min', videoUrl: 'https://www.youtube.com/embed/E03gh1huvW4', order: 7 },
    ],
  },
  {
    title: 'Product Management Fundamentals',
    description: 'Learn product management from the ground up. Product discovery, roadmapping, OKRs, user stories, agile ceremonies, stakeholder management, and launching your first product.',
    shortDescription: 'Learn PM from scratch — discovery, roadmaps, OKRs, and launch.',
    instructor: 'Jessica Nguyen',
    instructorBio: 'VP of Product at Stripe, former PM at Google and Facebook.',
    category: 'Business & Finance',
    level: 'Beginner',
    duration: '30 hours',
    price: 74.99,
    isFree: false,
    thumbnail: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&q=80',
    previewVideoUrl: 'https://www.youtube.com/embed/_Aj_sNPHxiE',
    rating: 4.8,
    reviewCount: 2100,
    enrolledCount: 14500,
    tags: ['Product Management', 'Agile', 'Roadmap', 'OKRs', 'Business'],
    lessons: [
      { title: 'What Does a PM Do?', duration: '15 min', videoUrl: 'https://www.youtube.com/embed/_Aj_sNPHxiE', order: 1 },
      { title: 'Product Discovery', duration: '30 min', videoUrl: 'https://www.youtube.com/embed/_Aj_sNPHxiE', order: 2 },
      { title: 'User Research Methods', duration: '28 min', videoUrl: 'https://www.youtube.com/embed/_Aj_sNPHxiE', order: 3 },
      { title: 'Writing User Stories', duration: '25 min', videoUrl: 'https://www.youtube.com/embed/_Aj_sNPHxiE', order: 4 },
      { title: 'Prioritization Frameworks', duration: '32 min', videoUrl: 'https://www.youtube.com/embed/_Aj_sNPHxiE', order: 5 },
      { title: 'OKRs & Metrics', duration: '30 min', videoUrl: 'https://www.youtube.com/embed/_Aj_sNPHxiE', order: 6 },
      { title: 'Roadmapping & Launch', duration: '38 min', videoUrl: 'https://www.youtube.com/embed/_Aj_sNPHxiE', order: 7 },
    ],
  },
  {
    title: 'Introduction to AI & Prompt Engineering',
    description: 'Understand how AI works and master the art of prompt engineering for GPT-4, Claude, Gemini, and Midjourney. Build AI-powered apps without writing complex code.',
    shortDescription: 'Master prompt engineering and build AI apps — no ML required.',
    instructor: 'Ava Thompson',
    instructorBio: 'AI researcher, prompt engineer at Anthropic, and educator.',
    category: 'AI & Machine Learning',
    level: 'Beginner',
    duration: '18 hours',
    price: 0,
    isFree: true,
    thumbnail: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&q=80',
    previewVideoUrl: 'https://www.youtube.com/embed/T2DXrs0OpHU',
    rating: 4.8,
    reviewCount: 6700,
    enrolledCount: 52000,
    tags: ['AI', 'Prompt Engineering', 'ChatGPT', 'LLMs', 'Beginner'],
    lessons: [
      { title: 'What is AI? Simple Explained', duration: '12 min', videoUrl: 'https://www.youtube.com/embed/T2DXrs0OpHU', order: 1 },
      { title: 'How LLMs Work', duration: '20 min', videoUrl: 'https://www.youtube.com/embed/T2DXrs0OpHU', order: 2 },
      { title: 'Prompt Engineering Basics', duration: '25 min', videoUrl: 'https://www.youtube.com/embed/T2DXrs0OpHU', order: 3 },
      { title: 'Advanced Prompt Patterns', duration: '30 min', videoUrl: 'https://www.youtube.com/embed/T2DXrs0OpHU', order: 4 },
      { title: 'AI Image Generation', duration: '22 min', videoUrl: 'https://www.youtube.com/embed/T2DXrs0OpHU', order: 5 },
      { title: 'Building with the OpenAI API', duration: '35 min', videoUrl: 'https://www.youtube.com/embed/T2DXrs0OpHU', order: 6 },
      { title: 'AI Ethics & Limitations', duration: '18 min', videoUrl: 'https://www.youtube.com/embed/T2DXrs0OpHU', order: 7 },
    ],
  },
  {
    title: 'Docker & Containerization',
    description: 'Master Docker from the ground up. Containers, images, Dockerfile, Docker Compose, multi-stage builds, container registries, and deploying containerized apps to the cloud.',
    shortDescription: 'Master Docker and containerization for modern software delivery.',
    instructor: 'Ben Clarke',
    instructorBio: 'Docker Captain and principal DevOps engineer at GitLab.',
    category: 'DevOps & Cloud',
    level: 'Beginner',
    duration: '22 hours',
    price: 59.99,
    isFree: false,
    thumbnail: 'https://images.unsplash.com/photo-1605745341112-85968b19335b?w=800&q=80',
    previewVideoUrl: 'https://www.youtube.com/embed/3c-iBn73dDE',
    rating: 4.8,
    reviewCount: 2800,
    enrolledCount: 20000,
    tags: ['Docker', 'Containers', 'DevOps', 'CI/CD'],
    lessons: [
      { title: 'What are Containers?', duration: '15 min', videoUrl: 'https://www.youtube.com/embed/3c-iBn73dDE', order: 1 },
      { title: 'Docker Images & Layers', duration: '25 min', videoUrl: 'https://www.youtube.com/embed/3c-iBn73dDE', order: 2 },
      { title: 'Writing Dockerfiles', duration: '30 min', videoUrl: 'https://www.youtube.com/embed/3c-iBn73dDE', order: 3 },
      { title: 'Volumes & Networking', duration: '28 min', videoUrl: 'https://www.youtube.com/embed/3c-iBn73dDE', order: 4 },
      { title: 'Docker Compose', duration: '35 min', videoUrl: 'https://www.youtube.com/embed/3c-iBn73dDE', order: 5 },
      { title: 'Multi-Stage Builds', duration: '25 min', videoUrl: 'https://www.youtube.com/embed/3c-iBn73dDE', order: 6 },
      { title: 'Pushing to Registries', duration: '20 min', videoUrl: 'https://www.youtube.com/embed/3c-iBn73dDE', order: 7 },
    ],
  },
  {
    title: 'Vue.js 3 Complete Course',
    description: 'Learn Vue.js 3 from scratch with the Composition API. Build dynamic SPAs, state management with Pinia, Vue Router, and deploy a full real-world application.',
    shortDescription: 'Master Vue 3 Composition API, Pinia, and Vue Router.',
    instructor: 'Pierre Laurent',
    instructorBio: 'Vue.js core team contributor and open source educator.',
    category: 'Web Development',
    level: 'Intermediate',
    duration: '36 hours',
    price: 79.99,
    isFree: false,
    thumbnail: 'https://images.unsplash.com/photo-1593720219276-0b1eacd0aef4?w=800&q=80',
    previewVideoUrl: 'https://www.youtube.com/embed/ZqgiuPt5QZo',
    rating: 4.7,
    reviewCount: 1340,
    enrolledCount: 9100,
    tags: ['Vue.js', 'JavaScript', 'Frontend', 'Pinia', 'SPA'],
    lessons: [
      { title: 'Vue 3 Basics', duration: '20 min', videoUrl: 'https://www.youtube.com/embed/ZqgiuPt5QZo', order: 1 },
      { title: 'Composition API', duration: '35 min', videoUrl: 'https://www.youtube.com/embed/ZqgiuPt5QZo', order: 2 },
      { title: 'Reactivity & Computed', duration: '28 min', videoUrl: 'https://www.youtube.com/embed/ZqgiuPt5QZo', order: 3 },
      { title: 'Components & Props', duration: '30 min', videoUrl: 'https://www.youtube.com/embed/ZqgiuPt5QZo', order: 4 },
      { title: 'Vue Router', duration: '32 min', videoUrl: 'https://www.youtube.com/embed/ZqgiuPt5QZo', order: 5 },
      { title: 'Pinia State Management', duration: '38 min', videoUrl: 'https://www.youtube.com/embed/ZqgiuPt5QZo', order: 6 },
      { title: 'Build & Deploy', duration: '25 min', videoUrl: 'https://www.youtube.com/embed/ZqgiuPt5QZo', order: 7 },
    ],
  },
  {
    title: 'Android Development with Kotlin',
    description: 'Build modern Android apps using Kotlin and Jetpack Compose. Covers MVVM architecture, Room database, Retrofit, Coroutines, and publishing to the Google Play Store.',
    shortDescription: 'Build modern Android apps with Kotlin and Jetpack Compose.',
    instructor: 'Tomás García',
    instructorBio: 'Google Developer Expert in Android, building apps with 10M+ downloads.',
    category: 'Mobile Development',
    level: 'Intermediate',
    duration: '48 hours',
    price: 89.99,
    isFree: false,
    thumbnail: 'https://images.unsplash.com/photo-1580121441575-41bcb5c6b47c?w=800&q=80',
    previewVideoUrl: 'https://www.youtube.com/embed/EExSSotojVI',
    rating: 4.7,
    reviewCount: 1240,
    enrolledCount: 8700,
    tags: ['Android', 'Kotlin', 'Jetpack Compose', 'Mobile'],
    lessons: [
      { title: 'Kotlin Basics', duration: '28 min', videoUrl: 'https://www.youtube.com/embed/EExSSotojVI', order: 1 },
      { title: 'Jetpack Compose Intro', duration: '35 min', videoUrl: 'https://www.youtube.com/embed/EExSSotojVI', order: 2 },
      { title: 'MVVM Architecture', duration: '40 min', videoUrl: 'https://www.youtube.com/embed/EExSSotojVI', order: 3 },
      { title: 'Room Database', duration: '35 min', videoUrl: 'https://www.youtube.com/embed/EExSSotojVI', order: 4 },
      { title: 'Retrofit & Coroutines', duration: '38 min', videoUrl: 'https://www.youtube.com/embed/EExSSotojVI', order: 5 },
      { title: 'Navigation Component', duration: '30 min', videoUrl: 'https://www.youtube.com/embed/EExSSotojVI', order: 6 },
      { title: 'Publishing to Play Store', duration: '22 min', videoUrl: 'https://www.youtube.com/embed/EExSSotojVI', order: 7 },
    ],
  },
  {
    title: 'Content Marketing & Brand Building',
    description: 'Learn how to build a powerful brand through content marketing. Covers content strategy, blogging, YouTube, podcasting, social media, and building a loyal audience.',
    shortDescription: 'Build a brand and loyal audience through strategic content marketing.',
    instructor: 'Amara Obi',
    instructorBio: 'Brand strategist and content creator with 2M+ followers across platforms.',
    category: 'Digital Marketing',
    level: 'Beginner',
    duration: '24 hours',
    price: 54.99,
    isFree: false,
    thumbnail: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=800&q=80',
    previewVideoUrl: 'https://www.youtube.com/embed/paZ4E8XV74k',
    rating: 4.6,
    reviewCount: 1870,
    enrolledCount: 13000,
    tags: ['Content Marketing', 'Brand Building', 'Social Media', 'YouTube'],
    lessons: [
      { title: 'Content Strategy Basics', duration: '20 min', videoUrl: 'https://www.youtube.com/embed/paZ4E8XV74k', order: 1 },
      { title: 'Finding Your Niche', duration: '22 min', videoUrl: 'https://www.youtube.com/embed/paZ4E8XV74k', order: 2 },
      { title: 'Blogging for Authority', duration: '28 min', videoUrl: 'https://www.youtube.com/embed/paZ4E8XV74k', order: 3 },
      { title: 'YouTube Content Strategy', duration: '35 min', videoUrl: 'https://www.youtube.com/embed/paZ4E8XV74k', order: 4 },
      { title: 'Social Media Mastery', duration: '30 min', videoUrl: 'https://www.youtube.com/embed/paZ4E8XV74k', order: 5 },
      { title: 'Email List Building', duration: '25 min', videoUrl: 'https://www.youtube.com/embed/paZ4E8XV74k', order: 6 },
      { title: 'Monetizing Your Brand', duration: '32 min', videoUrl: 'https://www.youtube.com/embed/paZ4E8XV74k', order: 7 },
    ],
  },
];

const seed = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI, { dbName: 'learnpro' });
    console.log('✅ Connected to MongoDB');

    await Course.deleteMany({});
    console.log('🗑️  Cleared existing courses');

    const coursesWithSlugs = courses.map((course) => ({
      ...course,
      slug: slugify(course.title),
    }));

    const inserted = await Course.insertMany(coursesWithSlugs);
    console.log(`🌱 Seeded ${inserted.length} courses successfully`);

    await User.deleteOne({ email: 'demo@learnpro.com' });
    await User.create({
      name: 'Anubhab Das',
      email: 'demo@learnpro.com',
      password: 'Demo@1234',
      role: 'student',
    });
    console.log('👤 Demo user created: demo@learnpro.com / Demo@1234');

    await mongoose.disconnect();
    console.log('✅ Seeding complete. Disconnected.');
    process.exit(0);
  } catch (err) {
    console.error('❌ Seed failed:', err);
    process.exit(1);
  }
};

seed();